export const arData = [
    {
        "name": "Pyramid of Djoser",
        "yearBuilt": "2667–2648 BC",
        "style": "Ancient Egyptian",
        "buildingType": "",
        "scale": "",
        "location": "Saqqara, Egypt",
        "continent": "",
        "description": "",
        "image": "",
        "code":"POD"
    },
    {
        "name": "Great Pyramid of Giza",
        "yearBuilt": "2589-2566",
        "style": "Ancient Egyptian",
        "buildingType": "",
        "scale": "",
        "location": "Giza Egypt",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GPG"
    },
    {
        "name": "Hypostyle Hall of the Karnak Temple Complex",
        "yearBuilt": "1294-1213 BC",
        "style": "Ancient Egyptian",
        "buildingType": "",
        "scale": "",
        "location": "Luxor, Egypt",
        "continent": "",
        "description": "",
        "image": "",
        "code":"HHK"
    },
    {
        "name": "Great Temple of Abu Simbel",
        "yearBuilt": "1264 BC",
        "style": "Ancient Egyptian",
        "buildingType": "",
        "scale": "",
        "location": "Egypt",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GTA"
    },
    {
        "name": "Temple of Hephaestus",
        "yearBuilt": "449 BC",
        "style": "Greek",
        "buildingType": "",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "code":"TOH"
    },
    {
        "name": "Erechtheion",
        "yearBuilt": "421-405 BC",
        "style": "Greek",
        "buildingType": "",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ERE"
    },
    {
        "name": "Parthenon",
        "yearBuilt": "447-432 BC",
        "style": "Greek",
        "buildingType": "",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PAR"
    },
    {
        "name": "Ancient Theatre of Epidaurus",
        "yearBuilt": "3rd century BC",
        "style": "Greek",
        "buildingType": "",
        "scale": "",
        "location": "Epidaurus, Greece",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ATE"
    },
    {
        "name": "Colosseum",
        "yearBuilt": "70-80 BC",
        "style": "Roman",
        "buildingType": "",
        "scale": "",
        "location": "Rome",
        "continent": "",
        "description": "",
        "image": "",
        "code":"COL"
    },
    {
        "name": "Pont du Gard",
        "yearBuilt": "40-60 AD",
        "style": "Roman",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "Roman aqueduct",
        "image": "",
        "code":"PDG"
    },
    {
        "name": "Pantheon",
        "yearBuilt": "114-123",
        "style": "Roman",
        "buildingType": "",
        "scale": "",
        "location": "Rome",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PAN"
    },
    {
        "name": "Library of Celsus",
        "yearBuilt": "112-120",
        "style": "Roman",
        "buildingType": "",
        "scale": "",
        "location": "Ephesus, Turkey",
        "continent": "",
        "description": "",
        "image": "",
        "code":"LoC"
    },
    {
        "name": "Arch of Constantine",
        "yearBuilt": "316",
        "style": "Roman",
        "buildingType": "",
        "scale": "",
        "location": "Rome",
        "continent": "",
        "description": "",
        "image": "",
        "code":"AoC"
    },
    {
        "name": "Avenue of Dead",
        "yearBuilt": "1-600",
        "style": "Pre-Columbian",
        "buildingType": "",
        "scale": "",
        "location": "Teotihuacan, Mexico",
        "continent": "",
        "description": "",
        "image": "",
        "code":"AoD"
    },
    {
        "name": "Palace of Palenque",
        "yearBuilt": "7th-8th centuries",
        "style": "Pre-Columbian",
        "buildingType": "",
        "scale": "",
        "location": "Chiapas, Mexico",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PoP"
    },
    {
        "name": "Temple of the Great Jaguar",
        "yearBuilt": "732",
        "style": "Pre-Columbian",
        "buildingType": "",
        "scale": "",
        "location": "Tikal, Guatemala",
        "continent": "",
        "description": "",
        "image": "",
        "code":"TGJ"
    },
    {
        "name": "Nunnery Quadrangle",
        "yearBuilt": "800-1000",
        "style": "Pre-Columbian",
        "buildingType": "",
        "scale": "",
        "location": "Yucatan, Mexico",
        "continent": "",
        "description": "",
        "image": "",
        "code":"NUQ"
    },
    {
        "name": "Temple of the Warriors",
        "yearBuilt": "900-1200",
        "style": "Pre-Columbian",
        "buildingType": "",
        "scale": "",
        "location": "Yucatan, Mexico",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ToW"
    },
    {
        "name": "Great Stupa of Sanchi",
        "yearBuilt": "100 BC",
        "style": "Ancient Buddhist",
        "buildingType": "",
        "scale": "",
        "location": "Madhya Pradesh, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GSS"
    },
    {
        "name": "Somapura Mahavihara",
        "yearBuilt": "8th century AD",
        "style": "Ancient Buddhist",
        "buildingType": "",
        "scale": "",
        "location": "Bangladesh",
        "continent": "",
        "description": "",
        "image": "",
        "code":"SoM"
    },
    {
        "name": "Cave 19 of the Ajanta Caves",
        "yearBuilt": "5th century",
        "style": "Ancient Buddhist",
        "buildingType": "",
        "scale": "",
        "location": "India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"CAC"
    },{
        "name": "Hawa Mahal",
        "yearBuilt": "1799",
        "style": "Maru Gurjara",
        "buildingType": "",
        "scale": "",
        "location": "Jaipur, Rajasthan, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"HaM"
    },
    {
        "name": "Navlakha Temple",
        "yearBuilt": "12th century",
        "style": "Maru Gurjara",
        "buildingType": "",
        "scale": "",
        "location": "Ghumli, Gujarat, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"NaT"
    },
    {
        "name": "Jain Vimal Vasahi Temple",
        "yearBuilt": "1031",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "Mount Abu, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"JVV"
    },
    {
        "name": "Nyatapola Temple",
        "yearBuilt": "1702",
        "style": "Himalayan",
        "buildingType": "",
        "scale": "",
        "location": "Bhaktapur, Nepal",
        "continent": "",
        "description": "",
        "image": "",
        "code":"NyT"
    },
    {
        "name": "Paro Taktsang",
        "yearBuilt": "1692",
        "style": "Himalayan",
        "buildingType": "",
        "scale": "",
        "location": "Paro, Bhutan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PaT"
    },
    {
        "name": "Potala Palace",
        "yearBuilt": "1694",
        "style": "Himalayan",
        "buildingType": "",
        "scale": "",
        "location": "Lhasa, Tibet",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Pot"
    },
    {
        "name": "Jamia Masjid",
        "yearBuilt": "1394",
        "style": "Himalayan",
        "buildingType": "",
        "scale": "",
        "location": "Kashmir, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"JaM"
    },
    {
        "name": "Padmanabhaswamy Temple",
        "yearBuilt": "4th century AD",
        "style": "Dravidian",
        "buildingType": "Religious",
        "scale": "",
        "location": "India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Pad"
    },
    {
        "name": "Meenakshi Temple",
        "yearBuilt": "12th century",
        "style": "Dravidian",
        "buildingType": "",
        "scale": "",
        "location": "Tamil, Nadu, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Mee"
    },
    {
        "name": "Vitthala Temple",
        "yearBuilt": "16th century",
        "style": "Dravidian",
        "buildingType": "",
        "scale": "",
        "location": "Hampi, Kartanaka, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Vit"
    },
    {
        "name": "Giant Wild Goose Pagoda",
        "yearBuilt": "652",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Shaanxi, China",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GWG"
    },
    {
        "name": "Guanyian Pavilion of the Dule Monastery",
        "yearBuilt": "984",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Jixian, China",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GPD"
    },
    {
        "name": "Hall of Prayer for Good Harvests",
        "yearBuilt": "1703-1790",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Beijing, China",
        "continent": "",
        "description": "",
        "image": "",
        "code":"HPG"
    },
    {
        "name": "Temple of Literature",
        "yearBuilt": "1070",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Hanoi, Vietnam",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ToL"
    },
    {
        "name": "Gyeongbokgung Palace",
        "yearBuilt": "1395",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Seoul, South Korea",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GyP"
    },
    {
        "name": "Mausoleum of Emperor Nintoku",
        "yearBuilt": "4th century",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Sakai, Osaka Prefecture, Japan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"MEN"
    },
    {
        "name": "Pagoda at Hōryū-ji",
        "yearBuilt": "607",
        "style": "Sinosphere",
        "buildingType": "Religious",
        "scale": "",
        "location": "Nara Prefecture, Japan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PaH"
    },
    {
        "name": "Garden of the Ninna-ji Temple",
        "yearBuilt": "888",
        "style": "Sinosphere",
        "buildingType": "Garden",
        "scale": "",
        "location": "Kyoto, Japan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GNT"
    },
    {
        "name": "Kinkaku-ji",
        "yearBuilt": "1398",
        "style": "Sinosphere",
        "buildingType": "",
        "scale": "",
        "location": "Kyoto, Japan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Kin"
    },
    {
        "name": "Bakong",
        "yearBuilt": "9th century AD",
        "style": "Khmer",
        "buildingType": "",
        "scale": "",
        "location": "Hariharalaya, Roluos, Cambodia",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Bak"
    },
    {
        "name": "Prasat Prang Ku",
        "yearBuilt": "12th century",
        "style": "Khmer",
        "buildingType": "",
        "scale": "",
        "location": "Sisaket, Thailand",
        "continent": "",
        "description": "",
        "image": "",
        "code":"PPK"
    },
    {
        "name": "Angkor Wat",
        "yearBuilt": "12th century",
        "style": "Khmer",
        "buildingType": "",
        "scale": "",
        "location": "Angkor, Cambodia",
        "continent": "",
        "description": "",
        "image": "",
        "code":"AnW"
    },
    {
        "name": "Champa Temples",
        "yearBuilt": "4th century AD",
        "style": "Khmer",
        "buildingType": "",
        "scale": "",
        "location": "My Son, Vietnam",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Cha"
    },
    {
        "name": "Dome of the Rock",
        "yearBuilt": "691",
        "style": "Islamic",
        "buildingType": "",
        "scale": "",
        "location": "Jerusalem",
        "continent": "",
        "description": "",
        "image": "",
        "code":"DoR"
    },
    {
        "name": "Great Mosque of Samarra",
        "yearBuilt": "851",
        "style": "Islamic",
        "buildingType": "",
        "scale": "",
        "location": "Samarra, Iraq",
        "continent": "",
        "description": "",
        "image": "",
        "code":"GMS"
    },
    {
        "name": "Tomb of Shah Rukn-e-Alam",
        "yearBuilt": "1320-1324",
        "style": "Islamic",
        "buildingType": "",
        "scale": "",
        "location": "Multan, Pakistan",
        "continent": "",
        "description": "",
        "image": "",
        "code":"TSR"
    },
    {
        "name": "Court of the Lions",
        "yearBuilt": "1362-1391",
        "style": "Islamic",
        "buildingType": "",
        "scale": "",
        "location": "Alhambra, Granada, Spain",
        "continent": "",
        "description": "",
        "image": "",
        "code":"CoL"
    },
    {
        "name": "Taj Mahal",
        "yearBuilt": "1649",
        "style": "Islamic",
        "buildingType": "",
        "scale": "",
        "location": "Agra, India",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Taj"
    },
    {
        "name": "Basilica of Saint Sabina",
        "yearBuilt": "422-432",
        "style": "Byzantine",
        "buildingType": "",
        "scale": "",
        "location": "Aventine Hill, Rome",
        "continent": "",
        "description": "",
        "image": "",
        "code":"BSS"
    },
    {
        "name": "Hagia Irene",
        "yearBuilt": "6th century",
        "style": "Byzantine",
        "buildingType": "",
        "scale": "",
        "location": "Istanbul, Turkey",
        "continent": "",
        "description": "",
        "image": "",
        "code":"HaI"
    },
    {
        "name": "Basilica of San Vitale",
        "yearBuilt": "527-548",
        "style": "Byzantine",
        "buildingType": "",
        "scale": "",
        "location": "Ravenna, Italy",
        "continent": "",
        "description": "",
        "image": "",
        "code":"BSV"
    },
    {
        "name": "Basilica of Sant'Apollinare in Classe",
        "yearBuilt": "549",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Ravenna, Italy",
        "continent": "",
        "description": "",
        "image": "",
        "code":"BSC",
    },
    {
        "name": "Kapnikarea",
        "yearBuilt": "1050",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Kap"
    },
    {
        "name": "Hagia Sophia",
        "yearBuilt": "537",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Istanbul, Turkey",
        "continent": "",
        "description": "",
        "image": "",
        "code":"THS"
    },
    {
        "name": "St. Michael's Church",
        "yearBuilt": "1010-1031",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hildesheim, Germany",
        "continent": "",
        "description": "",
        "image": "",
        "code":"SMC"
    },
    {
        "name": "Abbey of Santo Domingo de Silos",
        "yearBuilt": "1085",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Santo Domingo de Silos, Spain",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ASD"
    },
    {
        "name": "Abbey Church of Sainte-Foy",
        "yearBuilt": "1087-1107",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Conques, France",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ACS"
    },
    {
        "name": "Durham Cathedral",
        "yearBuilt": "1093-1133",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Durham, UK",
        "continent": "",
        "description": "",
        "image": "",
        "code":"DuC"
    },
    {
        "name": "Maria Laach Abbey",
        "yearBuilt": "1093-1230",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Germany",
        "continent": "",
        "description": "",
        "image": "",
        "code":"MLA"
    },
    {
        "name": "Munsterkerk",
        "yearBuilt": "1220",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Netherlands",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Mun"
    },
    {
        "name": "Notre-Dame Cathedral",
        "yearBuilt": "1163",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "",
        "description": "",
        "image": "",
        "code":"NDC"
    },
    {
        "name": "Canterbury Cathedral",
        "yearBuilt": "1174-1184",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kent, UK",
        "continent": "",
        "description": "",
        "image": "",
        "code":"CaC"
    },
    {
        "name": "Chartres Cathedral",
        "yearBuilt": "1194-1250",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Chartres, France",
        "continent": "",
        "description": "",
        "image": "",
        "code":"ChC"
    },
    {
        "name": "Town Hall",
        "yearBuilt": "1376-1420",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Bruges, Belgium",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Tow"
    },
    {
        "name": "Hotel de Sens",
        "yearBuilt": "1475-1519",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "",
        "description": "",
        "image": "",
        "code":"HDS"
    },
    {
        "name": "Königsberg Cathedral",
        "yearBuilt": "1330-1380",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kaliningrad, Russia",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Kon"
    },
    {
        "name": "Ridderzaal",
        "yearBuilt": "1288",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hague, Netherlands",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Rid"
    },
    {
        "name": "Sainte-Chapelle",
        "yearBuilt": "1243-1248",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "",
        "description": "",
        "image": "",
        "code":"Sai"
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    },
    {
        "name": "",
        "yearBuilt": "",
        "style": "",
        "buildingType": "",
        "scale": "",
        "location": "",
        "continent": "",
        "description": "",
        "image": "",
        "code":""
    }
]