export const arData = [
    {
        "id": 1,
        "name": "Pyramid of Djoser",
        "yearBuilt": "2667–2648 BC",
        "style": "Ancient Egyptian",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Saqqara, Egypt",
        "continent": "Africa",
        "description": "",
        "image": "",
        "codename":"POD",
        "color": ""
    },
    {
        "id": 2,
        "name": "Great Pyramid of Giza",
        "yearBuilt": "2589-2566 BC",
        "style": "Ancient Egyptian",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Giza, Egypt",
        "continent": "Africa",
        "description": "",
        "image": "",
        "codename":"GPG",
        "color": ""
    },
    {
        "id": 3,
        "name": "Hypostyle Hall of the Karnak Temple Complex",
        "yearBuilt": "1294-1213 BC",
        "style": "Ancient Egyptian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Luxor, Egypt",
        "continent": "Africa",
        "description": "",
        "image": "",
        "codename":"HHK",
        "color": ""
    },
    {
        "id": 4,
        "name": "Great Temple of Abu Simbel",
        "yearBuilt": "1264 BC",
        "style": "Ancient Egyptian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Egypt",
        "continent": "Africa",
        "description": "",
        "image": "",
        "codename":"GTA",
        "color": ""
    },
    {
        "id": 5,
        "name": "Temple of Hephaestus",
        "yearBuilt": "449 BC",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"TOH",
        "color": ""
    },
    {
        "id": 6,
        "name": "Temple of Segesta",
        "yearBuilt": "400",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "Italy",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"TOS",
        "color": ""
    },
    {
        "id": 7,
        "name": "Erechtheion",
        "yearBuilt": "421-405 BC",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ERE",
        "color": ""
    },
    {
        "id": 8,
        "name": "Parthenon",
        "yearBuilt": "447-432 BC",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PAR",
        "color": ""
    },
    {
        "id": 9,
        "name": "Tholos of the Sanctuary of Athena Pronaia",
        "yearBuilt": "380-360 BC",
        "style": "Greek / Roman",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Delphi, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"TSP",
        "color": ""
    },
    {
        "id": 10,
        "name": "Ancient Theatre of Epidaurus",
        "yearBuilt": "300 BC",
        "style": "Greek / Roman",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Epidaurus, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ATE",
        "color": ""
    },
    {
        "id": 11,
        "name": "Colosseum",
        "yearBuilt": "70-80 BC",
        "style": "Greek / Roman",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"COL",
        "color": ""
    },
    {
        "id": 12,
        "name": "Pont du Gard",
        "yearBuilt": "40-60",
        "style": "Greek / Roman",
        "buildingType": "Utility",
        "scale": "",
        "location": "France",
        "continent": "Europe",
        "description": "Roman aqueduct",
        "image": "",
        "codename":"PDG",
        "color": ""
    },
    {
        "id": 13,
        "name": "Maison Carrée",
        "yearBuilt": "100",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"MCa",
        "color": ""
    },
    {
        "id": 14,
        "name": "Pantheon",
        "yearBuilt": "114-123",
        "style": "Greek / Roman",
        "buildingType": "Religious",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PAN",
        "color": ""
    },
    {
        "id": 15,
        "name": "Library of Celsus",
        "yearBuilt": "112-120",
        "style": "Greek / Roman",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Ephesus, Turkey",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"LoC","color": ""
    },
    {
        "id": 16,
        "name": "Arch of Constantine",
        "yearBuilt": "316",
        "style": "Greek / Roman",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"AoC",
        "color": ""
    },
    {
        "id": 17,
        "name": "Avenue of Dead",
        "yearBuilt": "1-600",
        "style": "Pre-Columbian",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Teotihuacan, Mexico",
        "continent": "South America",
        "description": "",
        "image": "",
        "codename":"AoD",
        "color": ""
    },
    {
        "id": 18,
        "name": "Palace of Palenque",
        "yearBuilt": "600",
        "style": "Pre-Columbian",
        "buildingType": "Residential",
        "scale": "",
        "location": "Chiapas, Mexico",
        "continent": "South America",
        "description": "",
        "image": "",
        "codename":"PoP",
        "color": ""
    },
    {
        "id": 19,
        "name": "Temple of the Great Jaguar",
        "yearBuilt": "732",
        "style": "Pre-Columbian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Tikal, Guatemala",
        "continent": "South America",
        "description": "",
        "image": "",
        "codename":"TGJ",
        "color": ""
    },
    {
        "id": 20,
        "name": "Nunnery Quadrangle",
        "yearBuilt": "800-1000",
        "style": "Pre-Columbian",
        "buildingType": "Residential",
        "scale": "",
        "location": "Yucatan, Mexico",
        "continent": "South America",
        "description": "",
        "image": "",
        "codename":"NUQ",
        "color": ""
    },
    {
        "id": 21,
        "name": "Temple of the Warriors",
        "yearBuilt": "900-1200",
        "style": "Pre-Columbian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Yucatan, Mexico",
        "continent": "South America",
        "description": "",
        "image": "",
        "codename":"ToW",
        "color": ""
    },
    {
        "id": 22,
        "name": "Great Stupa of Sanchi",
        "yearBuilt": "100 BC",
        "style": "Ancient Buddhist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Madhya Pradesh, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GSS",
        "color": ""
    },
    {
        "id": 23,
        "name": "Somapura Mahavihara",
        "yearBuilt": "700",
        "style": "Ancient Buddhist",
        "buildingType": "Religious",
        "scale": "",
        "location": "Bangladesh",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"SoM",
        "color": ""
    },
    {
        "id": 24,
        "name": "Ajanta Caves",
        "yearBuilt": "400",
        "style": "Ancient Buddhist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"AJC",
        "color": ""
    },{
        "id": 25,
        "name": "Hawa Mahal",
        "yearBuilt": "1799",
        "style": "Maru Gurjara",
        "buildingType": "Residential",
        "scale": "",
        "location": "Jaipur, Rajasthan, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"HaM",
        "color": ""
    },
    {
        "id": 26,
        "name": "Navlakha Temple",
        "yearBuilt": "1100",
        "style": "Maru Gurjara",
        "buildingType": "Religious",
        "scale": "",
        "location": "Ghumli, Gujarat, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"NaT",
        "color": ""
    },
    {
        "id": 27,
        "name": "Jain Vimal Vasahi Temple",
        "yearBuilt": "1031",
        "style": "Maru Gurjara",
        "buildingType": "Religious",
        "scale": "",
        "location": "Mount Abu, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"JVV",
        "color": ""
    },
    {
        "id": 28,
        "name": "Nyatapola Temple",
        "yearBuilt": "1702",
        "style": "Himalayan",
        "buildingType": "Religious",
        "scale": "",
        "location": "Bhaktapur, Nepal",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"NyT",
        "color": ""
    },
    {
        "id": 29,
        "name": "Paro Taktsang",
        "yearBuilt": "1692",
        "style": "Himalayan",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paro, Bhutan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"PaT",
        "color": ""
    },
    {
        "id": 30,
        "name": "Potala Palace",
        "yearBuilt": "1694",
        "style": "Himalayan",
        "buildingType": "Religious",
        "scale": "",
        "location": "Lhasa, Tibet",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Pot",
        "color": ""
    },
    {
        "id": 31,
        "name": "Jamia Masjid",
        "yearBuilt": "1394",
        "style": "Himalayan",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kashmir, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"JaM",
        "color": ""
    },
    {
        "id": 32,
        "name": "Temple of Padmanabhaswamy",
        "yearBuilt": "300",
        "style": "Dravidian",
        "buildingType": "Religious",
        "scale": "",
        "location": "India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Pad",
        "color": ""
    },
    {
        "id": 33,
        "name": "Meenakshi Temple",
        "yearBuilt": "1100",
        "style": "Dravidian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Tamil, Nadu, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Mee",
        "color": ""
    },
    {
        "id": 34,
        "name": "Vitthala Temple",
        "yearBuilt": "1500",
        "style": "Dravidian",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hampi, Kartanaka, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Vit",
        "color": ""
    },
    {
        "id": 35,
        "name": "Giant Wild Goose Pagoda",
        "yearBuilt": "652",
        "style": "Sinosphere",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Shaanxi, China",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GWG",
        "color": ""
    },
    {
        "id": 36,
        "name": "Guanyian Pavilion of the Dule Monastery",
        "yearBuilt": "984",
        "style": "Sinosphere",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Jixian, China",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GPD",
        "color": ""
    },
    {
        "id": 37,
        "name": "Hall of Prayer for Good Harvests",
        "yearBuilt": "1703-1790",
        "style": "Sinosphere",
        "buildingType": "Religious",
        "scale": "",
        "location": "Beijing, China",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"HPG",
        "color": ""
    },
    {
        "id": 38,
        "name": "Temple of Literature",
        "yearBuilt": "1070",
        "style": "Sinosphere",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Hanoi, Vietnam",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"ToL",
        "color": ""
    },
    {
        "id": 39,
        "name": "Gyeongbokgung Palace",
        "yearBuilt": "1395",
        "style": "Sinosphere",
        "buildingType": "Residential",
        "scale": "",
        "location": "Seoul, South Korea",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GyP",
        "color": ""
    },
    {
        "id": 40,
        "name": "Mausoleum of Emperor Nintoku",
        "yearBuilt": "300",
        "style": "Sinosphere",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Sakai, Osaka Prefecture, Japan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"MEN",
        "color": ""
    },
    {
        "id": 41,
        "name": "Hōryū-ji Pagoda",
        "yearBuilt": "607",
        "style": "Sinosphere",
        "buildingType": "Religious",
        "scale": "",
        "location": "Nara Prefecture, Japan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"PaH",
        "color": ""
    },
    {
        "id": 42,
        "name": "Garden of the Ninna-ji Temple",
        "yearBuilt": "888",
        "style": "Sinosphere",
        "buildingType": "Public Space",
        "scale": "",
        "location": "Kyoto, Japan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GNT",
        "color": ""
    },
    {
        "id": 43,
        "name": "Kinkaku-ji",
        "yearBuilt": "1398",
        "style": "Sinosphere",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kyoto, Japan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Kin",
        "color": ""
    },
    {
        "id": 44,
        "name": "Bakong Temple",
        "yearBuilt": "800",
        "style": "Khmer",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hariharalaya, Roluos, Cambodia",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Bak",
        "color": ""
    },
    {
        "id": 45,
        "name": "Prasat Prang Ku",
        "yearBuilt": "1100",
        "style": "Khmer",
        "buildingType": "Religious",
        "scale": "",
        "location": "Sisaket, Thailand",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"PPK",
        "color": ""
    },
    {
        "id": 46,
        "name": "Angkor Wat",
        "yearBuilt": "1100",
        "style": "Khmer",
        "buildingType": "Religious",
        "scale": "",
        "location": "Angkor, Cambodia",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"AnW",
        "color": ""
    },
    {
        "id": 47,
        "name": "Champa Temples",
        "yearBuilt": "300",
        "style": "Khmer",
        "buildingType": "Religious",
        "scale": "",
        "location": "My Son, Vietnam",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Cha",
        "color": ""
    },
    {
        "id": 48,
        "name": "Dome of the Rock",
        "yearBuilt": "691",
        "style": "Islamic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Jerusalem",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"DoR",
        "color": ""
    },
    {
        "id": 49,
        "name": "Great Mosque of Samarra",
        "yearBuilt": "851",
        "style": "Islamic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Samarra, Iraq",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"GMS",
        "color": ""
    },
    {
        "id": 50,
        "name": "Tomb of Shah Rukn-e-Alam",
        "yearBuilt": "1320-1324",
        "style": "Islamic",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Multan, Pakistan",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"TSR",
        "color": ""
    },
    {
        "id": 51,
        "name": "Court of the Lions",
        "yearBuilt": "1362-1391",
        "style": "Islamic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Alhambra, Granada, Spain",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CoL",
        "color": ""
    },
    {
        "id": 52,
        "name": "Taj Mahal",
        "yearBuilt": "1649",
        "style": "Islamic",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Agra, India",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Taj",
        "color": ""
    },
    {
        "id": 53,
        "name": "Basilica of Saint Sabina",
        "yearBuilt": "422-432",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Aventine Hill, Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BSS",
        "color": ""
    },
    {
        "id": 54,
        "name": "Hagia Irene",
        "yearBuilt": "500",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Istanbul, Turkey",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"HaI",
        "color": ""
    },
    {
        "id":55 ,
        "name": "Basilica of San Vitale",
        "yearBuilt": "527-548",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Ravenna, Italy",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BSV",
        "color": ""
    },
    {
        "id":56 ,
        "name": "Basilica of Sant'Apollinare in Classe",
        "yearBuilt": "549",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Ravenna, Italy",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BSC",
        "color": ""
    },
    {
        "id": 57,
        "name": "Kapnikarea",
        "yearBuilt": "1050",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Athens, Greece",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Kap",
        "color": ""
    },
    {
        "id": 58,
        "name": "Hagia Sophia",
        "yearBuilt": "537",
        "style": "Byzantine",
        "buildingType": "Religious",
        "scale": "",
        "location": "Istanbul, Turkey",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"THS",
        "color": ""
    },
    {
        "id": 59,
        "name": "St. Michael's Church",
        "yearBuilt": "1010-1031",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hildesheim, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"SMC",
        "color": ""
    },
    {
        "id": 60,
        "name": "Abbey of Santo Domingo de Silos",
        "yearBuilt": "1085",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Santo Domingo de Silos, Spain",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ASD",
        "color": ""
    },
    {
        "id": 61,
        "name": "Abbey Church of Sainte-Foy",
        "yearBuilt": "1087-1107",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Conques, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ACS",
        "color": ""
    },
    {
        "id": 62,
        "name": "Durham Cathedral",
        "yearBuilt": "1093-1133",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Durham, UK",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"DuC",
        "color": ""
    },
    {
        "id": 63,
        "name": "Maria Laach Abbey",
        "yearBuilt": "1093-1230",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"MLA",
        "color": ""
    },
    {
        "id": 64,
        "name": "Munsterkerk",
        "yearBuilt": "1220",
        "style": "Romanesque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Netherlands",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Mun",
        "color": ""
    },
    {
        "id": 65,
        "name": "Notre-Dame Cathedral",
        "yearBuilt": "1163",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"NDC",
        "color": ""
    },
    {
        "id": 66,
        "name": "Canterbury Cathedral",
        "yearBuilt": "1174-1184",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kent, UK",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CaC",
        "color": ""
    },
    {
        "id": 67,
        "name": "Chartres Cathedral",
        "yearBuilt": "1194-1250",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Chartres, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ChC",
        "color": ""
    },
    {
        "id": 68,
        "name": "Town Hall",
        "yearBuilt": "1376-1420",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Bruges, Belgium",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Tow",
        "color": ""
    },
    {
        "id": 69,
        "name": "Hotel de Sens",
        "yearBuilt": "1475-1519",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"HDS",
        "color": ""
    },
    {
        "id": 70,
        "name": "Königsberg Cathedral",
        "yearBuilt": "1330-1380",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Kaliningrad, Russia",
        "continent": "Asia",
        "description": "",
        "image": "",
        "codename":"Kon",
        "color": ""
    },
    {
        "id": 71,
        "name": "Ridderzaal",
        "yearBuilt": "1288",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Hague, Netherlands",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Rid",
        "color": ""
    },
    {
        "id": 72,
        "name": "Sainte-Chapelle",
        "yearBuilt": "1243-1248",
        "style": "Gothic",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Sai",
        "color": ""
    },
    {
        "id": 73,
        "name": "Florence Cathedral",
        "yearBuilt": "1294-1436",
        "style": "Rennaisance",
        "buildingType": "Religious",
        "scale": "",
        "location": "Florence, Italy",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"FlC","color": ""
    },
    {
        "id": 74,
        "name": "Basilica of Sant'Andrea",
        "yearBuilt": "1470",
        "style": "Rennaisance",
        "buildingType": "Religious",
        "scale": "",
        "location": "Mantua, Italy",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BSA","color": ""
    },
    {
        "id": 75,
        "name": "Tempietto, The",
        "yearBuilt": "1502",
        "style": "Rennaisance",
        "buildingType": "Religious",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Tem","color": ""
    },
    {
        "id": 76,
        "name": "Villa Madama",
        "yearBuilt": "1518-1525",
        "style": "Rennaisance",
        "buildingType": "Religious",
        "scale": "",
        "location": "outside Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ViM","color": ""
    },
    {
        "id": 77,
        "name": "Château d'Azay-le-Rideau",
        "yearBuilt": "1518-1527",
        "style": "Rennaisance",
        "buildingType": "Residential",
        "scale": "",
        "location": "Loire, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CAR","color": ""
    },
    {
        "id": 78,
        "name": "Château de Chambord",
        "yearBuilt": "1519-1547",
        "style": "Rennaisance",
        "buildingType": "Residential",
        "scale": "",
        "location": "Loire, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CdC","color": ""
    },
    {
        "id": 79,
        "name": "Farnese Palace",
        "yearBuilt": "1534-1546",
        "style": "Rennaisance",
        "buildingType": "Residential",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PaR","color": ""
    },
    {
        "id": 80,
        "name": "Temple du Marais",
        "yearBuilt": "1632",
        "style": "Baroque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"TdM","color": ""
    },
    {
        "id": 81,
        "name": "San Carlo alle Quattro Fontane",
        "yearBuilt": "1638-1677",
        "style": "Baroque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"SCQ","color": ""
    },
    {
        "id": 82,
        "name": "St. Peter's Square",
        "yearBuilt": "1656-1667",
        "style": "Baroque",
        "buildingType": "Public Space",
        "scale": "",
        "location": "Rome",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"SPQ","color": ""
    },
    {
        "id": 83,
        "name": "Gardens at Vaux-le-Vicomte",
        "yearBuilt": "1657-1661",
        "style": "Baroque",
        "buildingType": "Public Space",
        "scale": "",
        "location": "France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"GVV","color": ""
    },
    {
        "id": 84,
        "name": "Dôme des Invalides",
        "yearBuilt": "1677-1706",
        "style": "Baroque",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"DdI","color": ""
    },
    {
        "id": 85,
        "name": "Royal Naval Hospital",
        "yearBuilt": "1695-1715",
        "style": "Baroque",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Greenwich, London",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"RVH","color": ""
    },
    {
        "id": 86,
        "name": "Church of Saint Nicholas",
        "yearBuilt": "1703-1711",
        "style": "Baroque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Prague, Czech Republic",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CSN","color": ""
    },
    {
        "id": 87,
        "name": "Karlskirche",
        "yearBuilt": "1715-1735",
        "style": "Baroque",
        "buildingType": "Religious",
        "scale": "",
        "location": "Vienna, Austria",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Kar","color": ""
    },
    {
        "id": 88,
        "name": "Royal Palace of Amsterdam",
        "yearBuilt": "1648-1665",
        "style": "Baroque",
        "buildingType": "Residential",
        "scale": "",
        "location": "Amsterdam, The Netherlands",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"RPA","color": ""
    },
    {
        "id": 89,
        "name": "Zwinger",
        "yearBuilt": "1719",
        "style": "Rococo",
        "buildingType": "Public Space",
        "scale": "",
        "location": "Dresden, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Zwi","color": ""
    },
    {
        "id": 90,
        "name": "Château St. Gerlach",
        "yearBuilt": "1735",
        "style": "Rococo",
        "buildingType": "Residential",
        "scale": "",
        "location": "The Netherlands",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CSG","color": ""
    },
    {
        "id": 91,
        "name": "Door of the Hôtel de Chenizot",
        "yearBuilt": "1719",
        "style": "Rococo",
        "buildingType": "Accessory",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"DHC","color": ""
    },
    {
        "id": 92,
        "name": "Queluz Palace",
        "yearBuilt": "1752",
        "style": "Rococo",
        "buildingType": "Residential",
        "scale": "",
        "location": "Lisbon, Portugal",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Qup","color": ""
    },
    {
        "id": 93,
        "name": "Pilgrimage Church of Wies",
        "yearBuilt": "1754",
        "style": "Rococo",
        "buildingType": "Religious",
        "scale": "",
        "location": "Steingaden, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PCW","color": ""
    },
    {
        "id": 94,
        "name": "English landscape garden at Stourhead",
        "yearBuilt": "1740",
        "style": "Neo-classicism",
        "buildingType": "Public Space",
        "scale": "",
        "location": "UK",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ELG","color": ""
    },
    {
        "id": 95,
        "name": "Panthéon (Paris)",
        "yearBuilt": "1758-1790",
        "style": "Neo-classicism",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PaP","color": ""
    },
    {
        "id": 96,
        "name": "Hôtel de la Marine",
        "yearBuilt": "1761-1770",
        "style": "Neo-classicism",
        "buildingType": "Residential",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"HdM","color": ""
    },
    {
        "id": 97,
        "name": "Stairway of the Grand Theater of Bordeaux",
        "yearBuilt": "1777-1780",
        "style": "Neo-classicism",
        "buildingType": "Accessory",
        "scale": "",
        "location": "Bordeaux, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"SGT","color": ""
    },
    {
        "id": 98,
        "name": "Villa Welgelegen",
        "yearBuilt": "1789",
        "style": "Neo-classicism",
        "buildingType": "Residential",
        "scale": "",
        "location": "Harlem, The Netherlands",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ViW","color": ""
    },
    {
        "id": 99,
        "name": "Neue Wache",
        "yearBuilt": "1816",
        "style": "Neo-classicism",
        "buildingType": "Memorial",
        "scale": "",
        "location": "Berlin, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"NeW","color": ""
    },
    {
        "id": 100,
        "name": "Burns Monument",
        "yearBuilt": "1820-1831",
        "style": "Neo-classicism",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Edinburgh, UK",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BuM","color": ""
    },
    {
        "id": 101,
        "name": "Petit Trianon",
        "yearBuilt": "1764",
        "style": "Neo-classicism",
        "buildingType": "Residential",
        "scale": "",
        "location": "Versailles, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PeT","color": ""
    },
    {
        "id": 102,
        "name": "Exterior of the Palais Garnier",
        "yearBuilt": "1860",
        "style": "Beaux Arts",
        "buildingType": "Accessory",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"EPG","color": ""
    },
    {
        "id": 103,
        "name": "Grand stairs of the Palais Garnier",
        "yearBuilt": "1860-1875",
        "style": "Beaux Arts",
        "buildingType": "Accessory",
        "scale": "",
        "location": "",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"GSP","color": ""
    },
    {
        "id": 104,
        "name": "The CEC Palace on Victory Avenue",
        "yearBuilt": "1897-1900",
        "style": "Beaux Arts",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Bucharest, Romania",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CEC","color": ""
    },
    {
        "id": 105,
        "name": "Cantacuzino Palace",
        "yearBuilt": "1898-1906",
        "style": "Beaux Arts",
        "buildingType": "Residential",
        "scale": "",
        "location": "Bucharest, Romania",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CaP","color": ""
    },
    {
        "id": 106,
        "name": "Petit Palais",
        "yearBuilt": "1900",
        "style": "Beaux Arts",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PeP","color": ""
    },
    {
        "id": 107,
        "name": "Grand Central Terminal",
        "yearBuilt": "1903",
        "style": "Beaux Arts",
        "buildingType": "Utility",
        "scale": "",
        "location": "New York City",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"GCT","color": ""
    },
    {
        "id": 108,
        "name": "Beaux Arts Villa",
        "yearBuilt": "1913",
        "style": "Beaux Arts",
        "buildingType": "Residential",
        "scale": "",
        "location": "Antwerp, Belgium",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BAV","color": ""
    },
    {
        "id": 109,
        "name": "Hôtel Tassel",
        "yearBuilt": "1894",
        "style": "Art Nouveau",
        "buildingType": "Residential",
        "scale": "",
        "location": "Brussels, Belgium",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"HoT","color": ""
    },
    {
        "id": 110,
        "name": "Secession Building",
        "yearBuilt": "1897",
        "style": "Art Nouveau",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Vienna, Austria",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"SeB","color": ""
    },
    {
        "id": 111,
        "name": "La Fermette Marbeuf",
        "yearBuilt": "1898",
        "style": "Art Nouveau",
        "buildingType": "Office / Commercial",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"LFM","color": ""
    },
    {
        "id": 112,
        "name": "Leonardo da Vinci Highschool",
        "yearBuilt": "1899",
        "style": "Art Nouveau",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"LVH","color": ""
    },
    {
        "id": 113,
        "name": "Bijouterie Fouquet",
        "yearBuilt": "1900",
        "style": "Art Nouveau",
        "buildingType": "Office / Commercial",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BiF","color": ""
    },
    {
        "id": 114,
        "name": "Porte Dauphine Métro Station",
        "yearBuilt": "1900",
        "style": "Art Nouveau",
        "buildingType": "Utility",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PDM","color": ""
    },
    {
        "id": 115,
        "name": "Maison Huot",
        "yearBuilt": "1903",
        "style": "Art Nouveau",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Nancy, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"MaH","color": ""
    },
    {
        "id": 116,
        "name": "Casa Batlló",
        "yearBuilt": "1904-1906",
        "style": "Art Nouveau",
        "buildingType": "Residential",
        "scale": "",
        "location": "Barcelona, Spain",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"CaB","color": ""
    },
    {
        "id": 117,
        "name": "Mița the Cyclist House",
        "yearBuilt": "1910",
        "style": "Art Nouveau",
        "buildingType": "Residential",
        "scale": "",
        "location": "Bucharest, Romania",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"MCH","color": ""
    },
    {
        "id": 118,
        "name": "Les Chardons Building",
        "yearBuilt": "1903",
        "style": "Art Nouveau",
        "buildingType": "Residential",
        "scale": "",
        "location": "Paris, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"LCB","color": ""
    },
    {
        "id": 119,
        "name": "Barcelona Pavilion",
        "yearBuilt": "1929",
        "style": "International",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Barcelona, Spain",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"BaP","color": ""
    },
    {
        "id": 120,
        "name": "Villa Savoye",
        "yearBuilt": "1929-1930",
        "style": "International",
        "buildingType": "Residential",
        "scale": "",
        "location": "Poissy, France",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"ViS","color": ""
    },
    {
        "id": 121,
        "name": "Lever House",
        "yearBuilt": "1952",
        "style": "International",
        "buildingType": "Residential",
        "scale": "",
        "location": "New York City",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"LeH","color": ""
    },
    {
        "id": 122,
        "name": "Seagram Building",
        "yearBuilt": "1958",
        "style": "International",
        "buildingType": "Office / Commercial",
        "scale": "",
        "location": "New York City",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"SBu","color": ""
    },
    {
        "id": 123,
        "name": "United States Air Force Academy Cadet Chapel",
        "yearBuilt": "1963",
        "style": "International",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Colorado, USA",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"UCC","color": ""
    },
    {
        "id": 124,
        "name": "Rudolph Hall",
        "yearBuilt": "1963",
        "style": "Brutalist",
        "buildingType": "Institutional",
        "scale": "",
        "location": "New Haven, Connecticut",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"RuH","color": ""
    },
    {
        "id": 125,
        "name": "Habitat 67",
        "yearBuilt": "1966-1967",
        "style": "Brutalist",
        "buildingType": "Residential",
        "scale": "",
        "location": "Montreal, Canada",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"H67","color": ""
    },
    {
        "id": 126,
        "name": "Geisel Library",
        "yearBuilt": "1970",
        "style": "Brutalist",
        "buildingType": "Institutional",
        "scale": "",
        "location": "San Diego, California, USA",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"GeL","color": ""
    },
    {
        "id": 127,
        "name": "Robarts Library",
        "yearBuilt": "1973",
        "style": "Brutalist",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Toronto, Canada",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"RoL","color": ""
    },
    {
        "id": 128,
        "name": "Freeway Park Fountain",
        "yearBuilt": "1976",
        "style": "Brutalist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Seattle, Washington, USA",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"FPF","color": ""
    },
    {
        "id": 129,
        "name": "Piazza d'Italia",
        "yearBuilt": "1978",
        "style": "Post-modern",
        "buildingType": "Public Space",
        "scale": "",
        "location": "New Orleans, USA",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"PdI","color": ""
    },
    {
        "id": 130,
        "name": "Neue Staatsgalerie",
        "yearBuilt": "1984",
        "style": "Post-modern",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Stuttgart, Germany",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"NeS","color": ""
    },
    {
        "id": 131,
        "name": "AT&T Headquarters",
        "yearBuilt": "1984",
        "style": "Post-modern",
        "buildingType": "Office / Commercial",
        "scale": "",
        "location": "New York City",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"ATT","color": ""
    },
    {
        "id": 132,
        "name": "Team Disney Building",
        "yearBuilt": "1990",
        "style": "Post-modern",
        "buildingType": "Office / Commercial",
        "scale": "",
        "location": "Los Angeles, USA",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"TDB","color": ""
    },
    {
        "id": 133,
        "name": "Bundeskanzleramt",
        "yearBuilt": "1997-2001",
        "style": "Post-modern",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Berlin, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"Bun","color": ""
    },
    {
        "id": 134,
        "name": "Wexner Center for the Arts",
        "yearBuilt": "1989",
        "style": "De-constructivist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Ohio, US",
        "continent": "North America",
        "description": "",
        "image": "",
        "codename":"WCA","color": ""
    },
    {
        "id": 135,
        "name": "Vitra Fire Station",
        "yearBuilt": "1989-1993",
        "style": "De-constructivist",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"VFS","color": ""
    },
    {
        "id": 136,
        "name": "Jewish Museum",
        "yearBuilt": "1992-1999",
        "style": "De-constructivist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Berlin, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"JeM","color": ""
    },
    {
        "id": 137,
        "name": "Guggenheim Museum",
        "yearBuilt": "1997",
        "style": "De-constructivist",
        "buildingType": "Cultural",
        "scale": "",
        "location": "Bilbao, Spain",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"GuM","color": ""
    },
    {
        "id": 138,
        "name": "Phaeno Science Center",
        "yearBuilt": "2005",
        "style": "De-constructivist",
        "buildingType": "Institutional",
        "scale": "",
        "location": "Wolfsburg, Germany",
        "continent": "Europe",
        "description": "",
        "image": "",
        "codename":"PSC"
    }
]